### ISSUE TITLE
Live preview/deployment of template

### ISSUE THREAD

**Issue by 0x0m0t0** [okupter/kitforstartups#13]
Hello, 

Would it be possible to re-upload a live preview of the template. It seems that the latest builds failed and the vercel links return errors.

The main url (https://kitforstartups.com) also returns directly towards the docs and not the actual template.

Thank you.

**Comment by JustinyAhin** [comment]
@0x0m0t0 working on that.
I should have a working demo in a couple hours /days

**Comment by JustinyAhin** [comment]
https://demo.kitforstartups.com/
